import type { OppDef } from "@/types/game";
import { TX } from "../art/keys";

/**
 * Mock Opp roster. First version ships Zeus (the overseer). Adding future Opps
 * is purely data: give them a spawn, texture, chatter, and status. The scene,
 * interaction system, speech bubbles, and Hall of Allies all read from here.
 */
export const opps: OppDef[] = [
  {
    id: "zeus",
    name: "Zeus",
    title: "King of Olympus - Pantheon Overseer",
    domain: "Oversees every Opp, sets decrees, and routes missions.",
    textureKey: TX.zeus,
    accent: "#f5c84c",
    spawn: { x: 1330, y: 1240 },
    wanderRadius: 52,
    status: "overseeing",
    activity: "Surveying Olympus and issuing decrees to the Pantheon.",
    task: "Decree: Establish the Olympus command network",
    greeting:
      "Welcome, Archon. Olympus is yours to command. Build your Hall, and the Pantheon shall follow.",
    homeLocationId: "temple-zeus",
    chatter: [
      "The Pantheon stirs...",
      "Build your Hall with care.",
      "I am watching every Opp.",
      "Drachmas shall flow like rivers.",
      "Summon your allies when ready.",
    ],
  },
  {
    id: "oracle",
    name: "The Oracle",
    title: "Seer of Delphi - Foresight & Research",
    domain: "Reads trends, predicts rising niches, and judges what is worth pursuing.",
    textureKey: TX.oracle,
    accent: "#aa8cff",
    spawn: { x: 1180, y: 1240 },
    wanderRadius: 44,
    status: "thinking",
    activity: "Scrying Pinterest and search winds for the next rising niche.",
    task: "Divine the launch niche for the print-on-demand store",
    greeting: "The vapors part for you, Archon. Ask, and I will read what is rising.",
    businessId: "stickers",
    divineGlow: true,
    chatter: [
      "The vapors stir...",
      "A trend rises in the east.",
      "The numbers do not lie.",
      "My prophecy is logged.",
    ],
  },
  {
    id: "apollo",
    name: "Apollo",
    title: "God of Art & Light - Print Workshop",
    domain: "Runs the print-on-demand art store: generates art and drafts listings.",
    textureKey: TX.apollo,
    accent: "#ffd86a",
    spawn: { x: 1480, y: 1240 },
    wanderRadius: 46,
    status: "drafting",
    activity: "Forging poster art and assembling Etsy drafts for your approval.",
    task: "Turn the Oracle's niche into listing drafts",
    greeting: "Light draws the eye, Archon. Name a niche and I will forge the listings.",
    businessId: "stickers",
    divineGlow: true,
    chatter: [
      "The press runs warm.",
      "Another draft awaits your seal.",
      "Art into drachmas.",
      "I publish nothing unbidden.",
    ],
  },
];

/**
 * Olympian council heads, reintroduced one at a time as the HQ is built out.
 * To bring a god into the world, move its entry into `opps` above and add the
 * id to the Pantheon `attendees` list in interiors.ts.
 */
export const futureGods: OppDef[] = [
  {
    id: "athena",
    name: "Athena",
    title: "Goddess of Wisdom - Head of the Academy",
    domain: "Runs the knowledge business: courses, guides, and strategy.",
    textureKey: TX.athena,
    accent: "#c9d1e6",
    spawn: { x: 2120, y: 1300 },
    wanderRadius: 46,
    status: "thinking",
    activity: "Plotting the quarter's course catalog and funnel strategy.",
    task: "Launch the 'Strategy of Olympus' course bundle",
    greeting: "Strategy wins wars, Archon. Tell me where to point the Academy.",
    businessId: "academy",
    divineGlow: true,
    chatter: ["Knowledge compounds.", "Measure, then strike.", "The funnel must flow."],
  },
  {
    id: "hermes",
    name: "Hermes",
    title: "Messenger God - Head of Logistics",
    domain: "Runs the dropshipping arm: sourcing, shipping, and fulfillment.",
    textureKey: TX.hermes,
    accent: "#6fd0a8",
    spawn: { x: 2700, y: 1320 },
    wanderRadius: 60,
    status: "running",
    activity: "Routing parcels across the realm and chasing carrier ETAs.",
    task: "Cut average delivery time to 3 days",
    greeting: "Fast feet, faster profits. What shall I move today?",
    businessId: "dropship",
    chatter: ["Speed is everything.", "Another parcel away!", "Carriers are behaving today."],
  },
  {
    id: "hephaestus",
    name: "Hephaestus",
    title: "God of the Forge - Head of the Etsy Workshop",
    domain: "Runs the flagship Etsy shop of handmade and made-to-order goods.",
    textureKey: TX.hephaestus,
    accent: "#e08a3a",
    spawn: { x: 2520, y: 1620 },
    wanderRadius: 40,
    status: "drafting",
    activity: "Hammering out new made-to-order listings for the Etsy shop.",
    task: "Restock the bestselling bronze laurel pendant",
    greeting: "The forge is hot. The Etsy orders never stop, Archon.",
    businessId: "etsy",
    chatter: ["The forge never cools.", "Another order fired.", "Quality over haste."],
  },
  {
    id: "poseidon",
    name: "Poseidon",
    title: "God of the Sea - Head of Imports",
    domain: "Runs overseas sourcing and wholesale across the sea routes.",
    textureKey: TX.poseidon,
    accent: "#34b3c9",
    spawn: { x: 900, y: 1340 },
    wanderRadius: 50,
    status: "scheduling",
    activity: "Negotiating wholesale crates arriving by sea.",
    task: "Secure the autumn container at better margin",
    greeting: "The tides bring goods from distant shores. Let us trade.",
    businessId: "imports",
    divineGlow: true,
    chatter: ["The tides are with us.", "A new shipment nears.", "Mind the margins."],
  },
  {
    id: "demeter",
    name: "Demeter",
    title: "Goddess of Harvest - Head of Subscriptions",
    domain: "Runs the recurring subscription-box harvest business.",
    textureKey: TX.demeter,
    accent: "#e0c266",
    spawn: { x: 520, y: 1500 },
    wanderRadius: 46,
    status: "running",
    activity: "Curating this month's harvest subscription boxes.",
    task: "Grow active subscribers past 1,000",
    greeting: "Plant well and the harvest recurs, Archon. Our subscribers grow.",
    businessId: "subscription",
    chatter: ["The harvest recurs.", "Retention is the root.", "Another box shipped."],
  },
];

export function getOpp(id: string): OppDef | undefined {
  return opps.find((o) => o.id === id);
}
